//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NesterovskyBros.Actions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NesterovskyBros.Actions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Items.
        /// </summary>
        internal static string Action_ClearItems {
            get {
                return ResourceManager.GetString("Action_ClearItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Item.
        /// </summary>
        internal static string Action_InsertItem {
            get {
                return ResourceManager.GetString("Action_InsertItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert {0}.
        /// </summary>
        internal static string Action_InsertItem2 {
            get {
                return ResourceManager.GetString("Action_InsertItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change {0}.
        /// </summary>
        internal static string Action_PropertyChange {
            get {
                return ResourceManager.GetString("Action_PropertyChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change {0} of {1}.
        /// </summary>
        internal static string Action_PropertyChange2 {
            get {
                return ResourceManager.GetString("Action_PropertyChange2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Item.
        /// </summary>
        internal static string Action_RemoveItem {
            get {
                return ResourceManager.GetString("Action_RemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove {0}.
        /// </summary>
        internal static string Action_RemoveItem2 {
            get {
                return ResourceManager.GetString("Action_RemoveItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Item.
        /// </summary>
        internal static string Action_SetItem {
            get {
                return ResourceManager.GetString("Action_SetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set {0}.
        /// </summary>
        internal static string Action_SetItem2 {
            get {
                return ResourceManager.GetString("Action_SetItem2", resourceCulture);
            }
        }
    }
}
